# Generated by Django 5.0.6 on 2024-05-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0002_rename_comments_comment_alter_category_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="categories",
        ),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(related_name="posts", to="Blog.category"),
        ),
    ]
