# Generated by Django 5.0.6 on 2024-05-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0003_remove_post_categories_post_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
