# Generated by Django 5.0.6 on 2024-05-27 01:43

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0006_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=tinymce.models.HTMLField(),
        ),
    ]
