# Generated by Django 5.0.6 on 2024-05-30 12:23

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_customuser_followed_categories"),
    ]

    operations = [
        migrations.RunSQL("""
            ALTER TABLE django_admin_log
            DROP CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id,
            ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id
            FOREIGN KEY (user_id)
            REFERENCES authentication_customuser (id)
            DEFERRABLE INITIALLY DEFERRED;
        """),
    ]

